services:

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_HOST}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  gateway-nginx:
    image: nginx:latest
    container_name: gateway-nginx
    ports:
      - "8000:80"
    volumes:
      - ./gateway:/var/www
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - gateway

  gateway:
    build: ./gateway
    container_name: gateway
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./gateway:/var/www
    depends_on:
      - db

  auth-nginx:
    image: nginx:latest
    container_name: auth-nginx
    ports:
      - "8001:80"
    volumes:
      - ./auth:/var/www
      - ./auth/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth

  auth:
    build: ./auth
    container_name: auth
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./auth:/var/www
    depends_on:
      - gateway